accumulate_grad_batches: 4
adam_epsilon: 1.0e-08
amp_backend: native
amp_level: O2
auto_lr_find: false
auto_scale_batch_size: false
auto_select_gpus: false
batch_size: 10
benchmark: false
bert_config_dir: /nfs/yding4/AVE_project/mrc-for-flat-nested-ner/yd_data/bert-base-cased
bert_dropout: 0.1
check_val_every_n_epoch: 1
checkpoint_callback: true
chinese: false
classifier_act_func: gelu
classifier_intermediate_hidden_size: 2048
data_dir: /nfs/yding4/AVE_project/consumable/title_bullet/33att/sample_data_1/mrc_for_ner/33_test/
default_root_dir: /nfs/yding4/AVE_project/mrc-for-flat-nested-ner/yd_script/01_18_2021/train_mrc_for_ner_test/mrc_ner
deterministic: false
distributed_backend: ddp
early_stop_callback: false
fast_dev_run: false
final_div_factor: 10000.0
flat: true
gpus: 2
gradient_clip_val: 1.0
limit_test_batches: 1.0
limit_train_batches: 1.0
limit_val_batches: 1.0
log_gpu_memory: null
log_save_interval: 100
logger: true
lr: 3.0e-05
lr_mini: 3.0e-07
lr_scheduler: polydecay
max_epochs: 20
max_keep_ckpt: 3
max_length: 200
max_steps: null
min_epochs: 1
min_steps: null
mrc_dropout: 0.3
num_nodes: 1
num_processes: 1
num_sanity_val_steps: 2
optimizer: torch.adam
overfit_batches: 0.0
overfit_pct: null
precision: 16
prepare_data_per_node: true
pretrained_checkpoint: ''
process_position: 0
profiler: null
progress_bar_refresh_rate: 1
reload_dataloaders_every_epoch: false
replace_sampler_ddp: true
resume_from_checkpoint: null
row_log_interval: 50
seed: 0
span_loss_candidates: pred_and_gold
sync_batchnorm: false
terminate_on_nan: false
test_percent_check: null
track_grad_norm: -1
train_percent_check: null
truncated_bptt_steps: null
val_check_interval: 0.2
val_percent_check: null
warmup_steps: 0
weight_decay: 0.01
weight_end: 1.0
weight_span: 0.1
weight_start: 1.0
weights_save_path: null
weights_summary: top
workers: 0
